### ISSUE TITLE
SeqMonk failed to start due to failed Memcheck

### ISSUE THREAD

**Issue by a7032018** [s-andrews/SeqMonk#55] opened 2018-01-25 19:12 UTC
System: Windows 7 x-64 Professional
Java Version: 1.8.0_161
I unzipped SeqMonk Ver 1.40 to Desktop and executed SeqMonk.exe. The following error message prevented me from launching the application 
------------------------------------------------------------------------------------------------------------
java version "1.8.0_161"
Java(TM) SE Runtime Environment (build 1.8.0_161-b12)
Java HotSpot(TM) 64-Bit Server VM (build 25.161-b12, mixed mode)
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Prefs check command is java -cp "C:\Users\xxx\Desktop\SeqMonk" uk.ac.babraham.Utilities.PrefsPrinter
Prefs file check failed :Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Found 64-bit JVM, setting memory ceiling to 8192m
Physical memory installed is 16256
Amount of memory to use is 10240
Memcheck command is java -cp "C:\Users\xxx\Desktop\SeqMonk" -Xmx10240m u
k.ac.babraham.Utilities.ReportMemoryUsage
Failed check with 10240:Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Memcheck command is java -cp "C:\Users\xxx\Desktop\SeqMonk" -Xmx9216m uk
.ac.babraham.Utilities.ReportMemoryUsage
Failed check with 9216:Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Memcheck command is java -cp "C:\Users\xxx\Desktop\SeqMonk" -Xmx8192m uk
.ac.babraham.Utilities.ReportMemoryUsage
Failed check with 8192:Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Memcheck command is java -cp "C:\Users\xxx\Desktop\SeqMonk" -Xmx7168m uk
.ac.babraham.Utilities.ReportMemoryUsage
Failed check with 7168:Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Memcheck command is java -cp "C:\Users\xxx\Desktop\SeqMonk" -Xmx6144m uk
.ac.babraham.Utilities.ReportMemoryUsage
Failed check with 6144:Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."

Memcheck repeatedly failed.  Giving up.
---------------------------------------------------------------------------------------------------------------
I tried to uninstall/reinstall Java and gave no luck.

Thanks,

Pei-Ju

**Comment by s-andrews** [comment] 2018-01-26 09:28
It looks like this is failing because of an extra spurious message which is being captured before the output the script is looking for.  Specifically it's the:

```
Picked up JAVA_TOOL_OPTIONS: -Djava.vendor="Sun Microsystems Inc."
```

Which is probably causing the problem.  I can recreate this failure if I add that variable to my environment.

A quick bit of googling says that this value gets added to some systems to work around a version detection bug in some oracle programs.  If you haven't explicitly added this then you can remove that environment variable to get things working.

In our script the problem is that the extra text is coming out on STDERR which we should be able to ignore, but we're capturing it and missing the desired text which only comes out on STDOUT.  We can probably fix this in the launcher to avoid these issues coming up again.

**Comment by s-andrews** [comment] 2018-01-26 09:40
Looking at the C# code we do do this correctly in that we split STDOUT and STDERR.  The problem is that we assume that anything coming out on STDERR means that it's failed.

I should probably check stdout first and if that's given sensible output then use that, regardless of whether there is anything in stderr.

**Comment by s-andrews** [comment] 2018-01-26 09:57
I've modified the launcher to do a proper check of the exit code rather than looking for an empty error stream to determine whether the memory check worked or not.  On my system this fixes things when I have the environment variable set.

Can you try downloading the updated binary at:

https://github.com/s-andrews/SeqMonk/blob/master/SeqMonk.exe?raw=true

..and replacing the current SeqMonk.exe which ships with SeqMonk.  This should get things working on your system.

I don't think it's worth putting out a new release just to fix this since it's pretty niche, but it the fixed version will be in the next release.

**Closed by s-andrews** 2018-01-26 09:57 UTC
Labels: bug

**Comment by a7032018** [comment] 2018-01-26 14:09
It works! Thanks for solving this problem.
